language: node_js
node_js: 
    - "stable"
before_script: 
#script: 
    #- "npm test"
#after_success:
#Specify which branches to build using a safelist, or blocklist branches that you do not want to be built:
# blocklist
# branches:
  #except:
  #- name of branch not to build
  #- name of branch not to build

# safelist
# branches:
  # only:
  #- name of branch to build
  #- name of branch to build
cache:
    directories: 
        - "node_modules"