
language: node_js
node_js: 
    - "stable"
before_script: 
    - "npm i -g jasmine-node"
script: 
    - "npm run cover"
after_script:
  - npm run coveralls
cache:
  directories:
    - "node_modules" 
